'use client'

import { motion } from 'framer-motion'
import { ShieldCheck } from 'lucide-react'
import { fadeUp, stagger, VIEWPORT } from '@/lib/motion'

/*
 * Every claim here describes something a student can do today. Four of these
 * cards used to promise software that does not exist — an AI study coach, a
 * homework scanner, a per-lesson report, recorded lessons — and one offered
 * payment methods that are not wired up. Parents read this page before paying,
 * so a card goes back only when the feature behind it ships.
 */
const FEATURES = [
  {
    n: '01',
    title: 'Progress by Standard',
    body: 'Every question is tagged to a real NCEA standard, so progress is measured against what is actually examined.',
  },
  {
    n: '02',
    title: 'Projected Grades',
    body: 'A projected grade per standard, built from your own marked work — shown with how much evidence it rests on, never as a bare verdict.',
  },
  {
    n: '03',
    title: 'What Moves the Needle',
    body: 'Alongside each projection, the specific topics holding it back. No guessing what to revise next.',
  },
  {
    n: '04',
    title: 'Marked by a Real Tutor',
    body: 'A person marks the work and decides what a parent sees. Nothing reaches your family without a tutor releasing it.',
  },
  {
    n: '05',
    title: 'Online or In Person',
    body: 'Live classes online, at your school, or in our local tutoring room. Materials stay available afterwards.',
  },
  {
    n: '06',
    title: 'Book and Pay in a Tap',
    body: 'Card payment through Stripe, with a receipt and an enrolment the moment it clears.',
  },
]

export default function Features() {
  return (
    <section
      aria-labelledby="features-heading"
      className="rounded-t-[60px] bg-white px-5 py-24 text-[#101010] sm:px-8 sm:py-32"
    >
      <div className="mx-auto max-w-6xl">
        <motion.h2
          id="features-heading"
          variants={fadeUp}
          initial="hidden"
          whileInView="visible"
          viewport={VIEWPORT}
          className="display max-w-4xl text-[clamp(2.4rem,7vw,5.5rem)] text-[#101010]"
        >
          What you actually get
        </motion.h2>

        <motion.ol
          variants={stagger}
          initial="hidden"
          whileInView="visible"
          viewport={VIEWPORT}
          className="mt-16 border-t border-black/10"
        >
          {FEATURES.map((f) => (
            <motion.li
              key={f.n}
              variants={fadeUp}
              className="group grid grid-cols-1 gap-2 border-b border-black/10 py-8 transition-colors duration-300 hover:bg-black/[0.02] sm:grid-cols-[5rem_1fr] sm:gap-8 md:grid-cols-[5rem_18rem_1fr]"
            >
              <span
                aria-hidden
                className="text-[0.85rem] font-medium tracking-[0.16em] text-accent-deep"
              >
                {f.n}
              </span>
              <h3 className="text-[clamp(1.25rem,2.4vw,1.75rem)] leading-tight font-semibold tracking-tight">
                {f.title}
              </h3>
              <p className="max-w-xl text-[0.98rem] leading-relaxed font-light text-[#4A5157]">
                {f.body}
              </p>
            </motion.li>
          ))}
        </motion.ol>

        {/* The trust boundary, stated once and in full. */}
        <motion.aside
          variants={fadeUp}
          initial="hidden"
          whileInView="visible"
          viewport={VIEWPORT}
          className="mt-14 flex flex-col gap-4 rounded-3xl border border-accent-deep/25 bg-[#FBF6E8] p-7 sm:flex-row sm:items-start sm:gap-6 sm:p-9"
        >
          <ShieldCheck
            size={26}
            aria-hidden
            className="shrink-0 text-accent-deep"
            strokeWidth={1.6}
          />
          <div>
            <h3 className="text-[1.15rem] font-semibold tracking-tight">
              Where the numbers come from
            </h3>
            <p className="mt-2 max-w-3xl text-[0.98rem] leading-relaxed font-light text-[#3E444A]">
              Every figure on your child's page is counted from their own marked work —
              no model guesses at it, and nothing here is generated by a chatbot. A
              projected grade reaches you only after a tutor has read it and can explain
              it, and no student's work is used to train shared or public models.
            </p>
          </div>
        </motion.aside>
      </div>
    </section>
  )
}
